//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.CodeFormatting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.CodeFormatting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit &apos;this&apos; is not necessary in reference to private field &apos;{0}&apos;.
        /// </summary>
        internal static string ExplicitThisAnalyzer_MessageFormat {
            get {
                return ResourceManager.GetString("ExplicitThisAnalyzer_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t use explicit &apos;this&apos; for private fields.
        /// </summary>
        internal static string ExplicitThisAnalyzer_Title {
            get {
                return ResourceManager.GetString("ExplicitThisAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &apos;this&apos; qualifier.
        /// </summary>
        internal static string ExplicitThisFixer_Title {
            get {
                return ResourceManager.GetString("ExplicitThisFixer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VariableTypeDeclaration.
        /// </summary>
        internal static string ExplicitVariableTypeAnalyzer_MessageFormat {
            get {
                return ResourceManager.GetString("ExplicitVariableTypeAnalyzer_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; should be declared with explicit type.
        /// </summary>
        internal static string ExplicitVariableTypeAnalyzer_Title {
            get {
                return ResourceManager.GetString("ExplicitVariableTypeAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the usage of &apos;var&apos; with explicit type.
        /// </summary>
        internal static string ExplicitVariableTypeFixer_Title {
            get {
                return ResourceManager.GetString("ExplicitVariableTypeFixer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is never written to and can be marked readonly.
        /// </summary>
        internal static string UnwrittenWritableFieldAnalyzer_MessageFormat {
            get {
                return ResourceManager.GetString("UnwrittenWritableFieldAnalyzer_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark unwritten fields readonly.
        /// </summary>
        internal static string UnwrittenWritableFieldAnalyzer_Title {
            get {
                return ResourceManager.GetString("UnwrittenWritableFieldAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark field as readonly.
        /// </summary>
        internal static string UnwrittenWritableFieldFixer_Title {
            get {
                return ResourceManager.GetString("UnwrittenWritableFieldFixer_Title", resourceCulture);
            }
        }
    }
}
